# AI-Powered Threat Detection & Response System - Service Installation Script
# Debre Berhan University - Department of IT
#
# This script installs the threat detection engine as a Windows Service using Task Scheduler.
# The service runs with highest privileges and starts automatically at system boot.
#
# REQUIREMENTS:
# - Administrator privileges
# - Python 3.10+ installed and in PATH
# - All dependencies installed (pip install -r requirements.txt)
# - Configuration file (config.yaml) properly configured

#Requires -RunAsAdministrator

param(
    [Parameter(Mandatory=$false)]
    [string]$PythonPath = "python",
    
    [Parameter(Mandatory=$false)]
    [string]$ProjectRoot = $PSScriptRoot | Split-Path -Parent,
    
    [Parameter(Mandatory=$false)]
    [string]$ServiceName = "AIThreatDefense",
    
    [Parameter(Mandatory=$false)]
    [ValidateSet("Install", "Uninstall", "Start", "Stop", "Restart", "Status")]
    [string]$Action = "Install"
)

# Service configuration
$ServiceDisplayName = "AI-Powered Threat Detection Service"
$ServiceDescription = "Real-time network threat detection using ML and automated response via Windows Firewall (Debre Berhan University)"
$TaskPath = "\AIThreatDefense\"

# Script paths
$DecisionEngineScript = Join-Path $ProjectRoot "src\decision_engine.py"
$ConfigFile = Join-Path $ProjectRoot "config.yaml"
$LogDir = Join-Path $ProjectRoot "logs"
$DataDir = Join-Path $ProjectRoot "data"

Write-Host "===============================================" -ForegroundColor Cyan
Write-Host "AI-Powered Threat Detection Service Manager" -ForegroundColor Cyan
Write-Host "Debre Berhan University - Department of IT" -ForegroundColor Cyan
Write-Host "===============================================" -ForegroundColor Cyan
Write-Host ""

# Function to check if running as administrator
function Test-Administrator {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

# Function to test Python installation
function Test-Python {
    try {
        $pythonVersion = & $PythonPath --version 2>&1
        Write-Host "✓ Python found: $pythonVersion" -ForegroundColor Green
        return $true
    }
    catch {
        Write-Host "✗ Python not found at: $PythonPath" -ForegroundColor Red
        Write-Host "  Please specify correct Python path with -PythonPath parameter" -ForegroundColor Yellow
        return $false
    }
}

# Function to test if required files exist
function Test-RequiredFiles {
    $allExist = $true
    
    $files = @{
        "Decision Engine" = $DecisionEngineScript
        "Configuration" = $ConfigFile
    }
    
    foreach ($file in $files.GetEnumerator()) {
        if (Test-Path $file.Value) {
            Write-Host "✓ $($file.Key): $($file.Value)" -ForegroundColor Green
        }
        else {
            Write-Host "✗ $($file.Key) not found: $($file.Value)" -ForegroundColor Red
            $allExist = $false
        }
    }
    
    return $allExist
}

# Function to create required directories
function Initialize-Directories {
    $dirs = @($LogDir, $DataDir)
    
    foreach ($dir in $dirs) {
        if (-not (Test-Path $dir)) {
            New-Item -ItemType Directory -Path $dir -Force | Out-Null
            Write-Host "✓ Created directory: $dir" -ForegroundColor Green
        }
    }
}

# Function to install service via Task Scheduler
function Install-Service {
    Write-Host "`nInstalling service..." -ForegroundColor Cyan
    
    # Create wrapper script for better control
    $wrapperScript = Join-Path $ProjectRoot "service\run_service.ps1"
    
    # Ensure service directory exists
    $serviceDir = Join-Path $ProjectRoot "service"
    if (-not (Test-Path $serviceDir)) {
        New-Item -ItemType Directory -Path $serviceDir -Force | Out-Null
    }
    
    # Create the wrapper script
    $wrapperContent = @"
# Service wrapper script - DO NOT EDIT MANUALLY
# Generated by install_service.ps1

Set-Location "$ProjectRoot"

`$pythonExe = "$PythonPath"
`$scriptPath = "$DecisionEngineScript"
`$configPath = "$ConfigFile"

Write-Host "Starting AI Threat Detection Service..." -ForegroundColor Green
Write-Host "Python: `$pythonExe" -ForegroundColor Gray
Write-Host "Script: `$scriptPath" -ForegroundColor Gray
Write-Host "Config: `$configPath" -ForegroundColor Gray
Write-Host ""

# Run the decision engine
& `$pythonExe `$scriptPath `$configPath

# If we get here, the service stopped
Write-Host "Service stopped." -ForegroundColor Yellow
"@
    
    Set-Content -Path $wrapperScript -Value $wrapperContent -Force
    Write-Host "✓ Created wrapper script: $wrapperScript" -ForegroundColor Green
    
    # Remove existing task if it exists
    $existingTask = Get-ScheduledTask -TaskName $ServiceName -ErrorAction SilentlyContinue
    if ($existingTask) {
        Write-Host "  Removing existing task..." -ForegroundColor Yellow
        Unregister-ScheduledTask -TaskName $ServiceName -Confirm:$false
    }
    
    # Create scheduled task action
    $action = New-ScheduledTaskAction `
        -Execute "PowerShell.exe" `
        -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$wrapperScript`"" `
        -WorkingDirectory $ProjectRoot
    
    # Create trigger (at startup)
    $trigger = New-ScheduledTaskTrigger -AtStartup
    
    # Create settings
    $settings = New-ScheduledTaskSettingsSet `
        -AllowStartIfOnBatteries `
        -DontStopIfGoingOnBatteries `
        -StartWhenAvailable `
        -RestartCount 3 `
        -RestartInterval (New-TimeSpan -Minutes 1) `
        -ExecutionTimeLimit (New-TimeSpan -Days 365)
    
    # Create principal (run as SYSTEM with highest privileges)
    $principal = New-ScheduledTaskPrincipal `
        -UserId "SYSTEM" `
        -LogonType ServiceAccount `
        -RunLevel Highest
    
    # Register the scheduled task
    try {
        Register-ScheduledTask `
            -TaskName $ServiceName `
            -TaskPath $TaskPath `
            -Action $action `
            -Trigger $trigger `
            -Settings $settings `
            -Principal $principal `
            -Description $ServiceDescription `
            -Force | Out-Null
        
        Write-Host "✓ Service installed successfully!" -ForegroundColor Green
        Write-Host ""
        Write-Host "Service Details:" -ForegroundColor Cyan
        Write-Host "  Name: $ServiceName" -ForegroundColor White
        Write-Host "  Display Name: $ServiceDisplayName" -ForegroundColor White
        Write-Host "  Task Path: $TaskPath$ServiceName" -ForegroundColor White
        Write-Host "  Status: Installed (not running)" -ForegroundColor White
        Write-Host ""
        Write-Host "To start the service, run:" -ForegroundColor Yellow
        Write-Host "  .\install_service.ps1 -Action Start" -ForegroundColor White
        
        return $true
    }
    catch {
        Write-Host "✗ Failed to install service: $_" -ForegroundColor Red
        return $false
    }
}

# Function to uninstall service
function Uninstall-Service {
    Write-Host "`nUninstalling service..." -ForegroundColor Cyan
    
    # Stop the service first
    Stop-Service
    
    # Remove scheduled task
    $task = Get-ScheduledTask -TaskName $ServiceName -ErrorAction SilentlyContinue
    if ($task) {
        try {
            Unregister-ScheduledTask -TaskName $ServiceName -Confirm:$false
            Write-Host "✓ Service uninstalled successfully!" -ForegroundColor Green
            return $true
        }
        catch {
            Write-Host "✗ Failed to uninstall service: $_" -ForegroundColor Red
            return $false
        }
    }
    else {
        Write-Host "  Service is not installed." -ForegroundColor Yellow
        return $true
    }
}

# Function to start service
function Start-Service {
    Write-Host "`nStarting service..." -ForegroundColor Cyan
    
    $task = Get-ScheduledTask -TaskName $ServiceName -ErrorAction SilentlyContinue
    if (-not $task) {
        Write-Host "✗ Service is not installed. Run with -Action Install first." -ForegroundColor Red
        return $false
    }
    
    try {
        Start-ScheduledTask -TaskName $ServiceName
        Start-Sleep -Seconds 2
        
        $taskInfo = Get-ScheduledTaskInfo -TaskName $ServiceName
        if ($taskInfo.LastTaskResult -eq 267009) {
            Write-Host "✓ Service started successfully!" -ForegroundColor Green
            Write-Host "  Check logs at: $LogDir" -ForegroundColor Yellow
            return $true
        }
        else {
            Write-Host "✓ Service start command sent." -ForegroundColor Green
            Write-Host "  Task Result Code: $($taskInfo.LastTaskResult)" -ForegroundColor Gray
            Write-Host "  Check logs for details: $LogDir" -ForegroundColor Yellow
            return $true
        }
    }
    catch {
        Write-Host "✗ Failed to start service: $_" -ForegroundColor Red
        return $false
    }
}

# Function to stop service
function Stop-Service {
    Write-Host "`nStopping service..." -ForegroundColor Cyan
    
    $task = Get-ScheduledTask -TaskName $ServiceName -ErrorAction SilentlyContinue
    if (-not $task) {
        Write-Host "  Service is not installed." -ForegroundColor Yellow
        return $true
    }
    
    try {
        Stop-ScheduledTask -TaskName $ServiceName -ErrorAction SilentlyContinue
        
        # Also kill any running Python processes for this service
        $pythonProcesses = Get-Process python* -ErrorAction SilentlyContinue | 
            Where-Object { $_.CommandLine -like "*decision_engine.py*" }
        
        if ($pythonProcesses) {
            Write-Host "  Stopping Python processes..." -ForegroundColor Gray
            $pythonProcesses | Stop-Process -Force
        }
        
        Write-Host "✓ Service stopped." -ForegroundColor Green
        return $true
    }
    catch {
        Write-Host "✗ Failed to stop service: $_" -ForegroundColor Red
        return $false
    }
}

# Function to restart service
function Restart-Service {
    Write-Host "`nRestarting service..." -ForegroundColor Cyan
    Stop-Service
    Start-Sleep -Seconds 2
    Start-Service
}

# Function to show service status
function Show-Status {
    Write-Host "`nService Status:" -ForegroundColor Cyan
    
    $task = Get-ScheduledTask -TaskName $ServiceName -ErrorAction SilentlyContinue
    
    if ($task) {
        $taskInfo = Get-ScheduledTaskInfo -TaskName $ServiceName
        
        Write-Host "  Installed: Yes" -ForegroundColor Green
        Write-Host "  State: $($task.State)" -ForegroundColor $(if ($task.State -eq "Running") { "Green" } else { "Yellow" })
        Write-Host "  Last Run: $($taskInfo.LastRunTime)" -ForegroundColor White
        Write-Host "  Last Result: $($taskInfo.LastTaskResult)" -ForegroundColor White
        Write-Host "  Next Run: $($taskInfo.NextRunTime)" -ForegroundColor White
        
        # Check if Python process is running
        $pythonProcesses = Get-Process python* -ErrorAction SilentlyContinue | 
            Where-Object { $_.CommandLine -like "*decision_engine.py*" }
        
        if ($pythonProcesses) {
            Write-Host "  Python Process: Running (PID: $($pythonProcesses.Id -join ', '))" -ForegroundColor Green
        }
        else {
            Write-Host "  Python Process: Not running" -ForegroundColor Yellow
        }
    }
    else {
        Write-Host "  Installed: No" -ForegroundColor Red
        Write-Host "  Run with -Action Install to install the service." -ForegroundColor Yellow
    }
}

# Main execution
Write-Host "Action: $Action" -ForegroundColor White
Write-Host "Project Root: $ProjectRoot" -ForegroundColor White
Write-Host ""

# Check administrator privileges
if (-not (Test-Administrator)) {
    Write-Host "✗ This script requires Administrator privileges!" -ForegroundColor Red
    Write-Host "  Please run PowerShell as Administrator and try again." -ForegroundColor Yellow
    exit 1
}

# For all actions except Status, validate prerequisites
if ($Action -ne "Status" -and $Action -ne "Uninstall") {
    Write-Host "Checking prerequisites..." -ForegroundColor Cyan
    
    if (-not (Test-Python)) {
        exit 1
    }
    
    if (-not (Test-RequiredFiles)) {
        Write-Host "`n✗ Required files are missing!" -ForegroundColor Red
        exit 1
    }
    
    Write-Host ""
}

# Execute requested action
$success = $false

switch ($Action) {
    "Install" {
        Initialize-Directories
        $success = Install-Service
    }
    "Uninstall" {
        $success = Uninstall-Service
    }
    "Start" {
        $success = Start-Service
    }
    "Stop" {
        $success = Stop-Service
    }
    "Restart" {
        $success = Restart-Service
    }
    "Status" {
        Show-Status
        $success = $true
    }
}

Write-Host ""
Write-Host "===============================================" -ForegroundColor Cyan

if ($success) {
    exit 0
}
else {
    exit 1
}
